title: <p align="center"> Logeshwaran V </p>
logo: <p align="center"> /assets/img/DSC_6781 a.jpg </p>
description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/lokeshwaran-vishwanthan-427428130">LinkedIn</a>

  
  
  

