title: <p align="center"> LOGESHWARAN V </p>
logo: /assets/img/DSC_6781 a.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/lokeshwaran-vishwanthan-427428130?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app">LinkedIn</a> |


  <br>   
  Passionate developer, committed to crafting clean code and building innovative solutions. 
  Constantly learning and adapting in the ever-evolving world of technology.
  Let us create something awesome together! 🚀 #GitCommit😉
  <br>
  

theme: jekyll-theme-minimal
