title: <p align="center"> Logeshwaran V </p>
logo: /assets/img/DSC_6781 a.jpg 
description:
  <p align="center">
  <a href="assets/img/LOGESHWARAN_RESUME.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/lokeshwaran-vishwanthan-427428130">LinkedIn</a>

  
  
  

